name: Build and Deploy AI Container with Depot

on: [push]

jobs:
  build:
    runs-on: depot-ubuntu-22.04  # Depot’s managed runner
    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Install Depot CLI
      - name: Install Depot CLI
        run: |
          curl -fsSL https://depot.dev/install.sh | sh
          echo "$HOME/.depot/bin" >> $GITHUB_PATH

      # Step 3: Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      # Step 4: Login to Depot
      - name: Login to Depot
        run: depot auth login --ci-token ${{ secrets.DEPOT_API_TOKEN }}

      # Step 5: Build Docker image with Depot
      - name: Build Docker Image with Depot
        run: depot build --cache --push depot-dev-github-actions-runners-quickstart:latest

      # Step 6: Configure AWS credentials
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: us-east-1

      # Step 7: Authenticate to Amazon ECR
      - name: Login to Amazon ECR
        run: |
          aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.us-east-1.amazonaws.com

      # Step 8: Tag Docker image
      - name: Tag Docker Image
        run: docker tag depot-dev-github-actions-runners-quickstart:latest ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.us-east-1.amazonaws.com/depot-dev-github-actions-runners-quickstart:latest

      # Step 9: Push Docker image to Amazon ECR
      - name: Push to Amazon ECR
        run: docker push ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.us-east-1.amazonaws.com/depot-dev-github-actions-runners-quickstart:latest
